#!/usr/bin/env python3
"""
Generate client/src/emoji_aliases.inc: gemoji-style shortcode aliases.

Source is the generated table in the Rust `emojis` crate (src/gen/mod.rs),
which carries the github/gemoji shortcodes (MIT). Only aliases whose glyph
exists in emoji_data.inc are emitted, and the canonical CLDR shortcodes
already in emoji_data.inc are skipped. EXTRA below holds hand-added spellings
gemoji lacks.

Usage:
    python3 emoji_aliases.gen.py path/to/emojis-X.Y.Z/src/gen/mod.rs > emoji_aliases.inc
"""
import os
import re
import sys

EXTRA = [
    ("🥃", "whiskey"),
    ("🥃", "whisky"),
    ("🥃", "bourbon"),
]

ROW = re.compile(
    r'Emoji \{ emoji: "([^"]+)".*?skin_tone: (None|Some\(\(\d+, \d+, SkinTone::\w+\)\)), '
    r'shortcodes: (None|Some\(&\[([^\]]*)\]\))'
)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "emoji_data.inc"), encoding="utf-8") as f:
        data = f.read()
    known = {}
    for m in re.finditer(r'\{"([^"]+)", "[^"]*", "[^"]*", Category::\w+, "([^"]*)"\}', data):
        known[m.group(1)] = set(m.group(2).split())

    out = []
    seen = set()

    def add(glyph, alias):
        if glyph not in known or alias in known[glyph] or (glyph, alias) in seen:
            return
        seen.add((glyph, alias))
        out.append((glyph, alias))

    with open(sys.argv[1], encoding="utf-8") as f:
        for line in f:
            m = ROW.search(line)
            if not m or m.group(2) not in ("None",) and "SkinTone::Default" not in m.group(2) or m.group(3) == "None":
                continue
            for sc in re.findall(r'"([^"]+)"', m.group(4)):
                add(m.group(1), sc)
    for g, a in EXTRA:
        add(g, a)

    print("// Generated by emoji_aliases.gen.py from github/gemoji shortcodes")
    print("// (MIT License, via the Rust `emojis` crate) plus hand-added spellings.")
    print("// Format: {glyph_utf8, alias}")
    for g, a in out:
        print('{"%s", "%s"},' % (g, a))


main()
