#pragma once

// Static table of common BCP-47/ISO 639-1 language codes + English display
// names, backing LanguagePicker's searchable dropdown for MSC4247 pronoun
// language tags. Names are plain English canonical forms — data values, like
// the app's existing free-text IANA timezone strings, not translated UI
// chrome (see CLAUDE.md's i18n rule, which applies to UI strings, not data).
//
// Not an exhaustive BCP-47/ISO 639-1 enumeration — a practical, commonly-used
// subset. Extend the table below if a language is missing.

#include <string_view>

namespace tesseract::views
{

struct Bcp47Language
{
    std::string_view code;
    std::string_view name;
};

inline constexpr Bcp47Language kBcp47Languages[] = {
    {"aa", "Afar"},
    {"ab", "Abkhazian"},
    {"af", "Afrikaans"},
    {"ak", "Akan"},
    {"sq", "Albanian"},
    {"am", "Amharic"},
    {"ar", "Arabic"},
    {"an", "Aragonese"},
    {"hy", "Armenian"},
    {"as", "Assamese"},
    {"av", "Avaric"},
    {"ae", "Avestan"},
    {"ay", "Aymara"},
    {"az", "Azerbaijani"},
    {"bm", "Bambara"},
    {"ba", "Bashkir"},
    {"eu", "Basque"},
    {"be", "Belarusian"},
    {"bn", "Bengali"},
    {"bi", "Bislama"},
    {"bs", "Bosnian"},
    {"br", "Breton"},
    {"bg", "Bulgarian"},
    {"my", "Burmese"},
    {"ca", "Catalan"},
    {"ch", "Chamorro"},
    {"ce", "Chechen"},
    {"ny", "Chichewa"},
    {"zh", "Chinese"},
    {"zh-Hans", "Chinese (Simplified)"},
    {"zh-Hant", "Chinese (Traditional)"},
    {"cu", "Church Slavic"},
    {"cv", "Chuvash"},
    {"kw", "Cornish"},
    {"co", "Corsican"},
    {"cr", "Cree"},
    {"hr", "Croatian"},
    {"cs", "Czech"},
    {"da", "Danish"},
    {"dv", "Divehi"},
    {"nl", "Dutch"},
    {"dz", "Dzongkha"},
    {"en", "English"},
    {"en-GB", "English (UK)"},
    {"en-US", "English (US)"},
    {"eo", "Esperanto"},
    {"et", "Estonian"},
    {"ee", "Ewe"},
    {"fo", "Faroese"},
    {"fj", "Fijian"},
    {"fi", "Finnish"},
    {"fr", "French"},
    {"fy", "Western Frisian"},
    {"ff", "Fulah"},
    {"gd", "Scottish Gaelic"},
    {"gl", "Galician"},
    {"lg", "Ganda"},
    {"ka", "Georgian"},
    {"de", "German"},
    {"el", "Greek"},
    {"kl", "Kalaallisut"},
    {"gn", "Guarani"},
    {"gu", "Gujarati"},
    {"ht", "Haitian Creole"},
    {"ha", "Hausa"},
    {"he", "Hebrew"},
    {"hz", "Herero"},
    {"hi", "Hindi"},
    {"ho", "Hiri Motu"},
    {"hu", "Hungarian"},
    {"is", "Icelandic"},
    {"io", "Ido"},
    {"ig", "Igbo"},
    {"id", "Indonesian"},
    {"ia", "Interlingua"},
    {"ie", "Interlingue"},
    {"iu", "Inuktitut"},
    {"ik", "Inupiaq"},
    {"ga", "Irish"},
    {"it", "Italian"},
    {"ja", "Japanese"},
    {"jv", "Javanese"},
    {"kn", "Kannada"},
    {"kr", "Kanuri"},
    {"ks", "Kashmiri"},
    {"kk", "Kazakh"},
    {"km", "Khmer"},
    {"ki", "Kikuyu"},
    {"rw", "Kinyarwanda"},
    {"ky", "Kyrgyz"},
    {"kv", "Komi"},
    {"kg", "Kongo"},
    {"ko", "Korean"},
    {"kj", "Kuanyama"},
    {"ku", "Kurdish"},
    {"lo", "Lao"},
    {"la", "Latin"},
    {"lv", "Latvian"},
    {"li", "Limburgish"},
    {"ln", "Lingala"},
    {"lt", "Lithuanian"},
    {"lu", "Luba-Katanga"},
    {"lb", "Luxembourgish"},
    {"mk", "Macedonian"},
    {"mg", "Malagasy"},
    {"ms", "Malay"},
    {"ml", "Malayalam"},
    {"mt", "Maltese"},
    {"gv", "Manx"},
    {"mi", "Maori"},
    {"mr", "Marathi"},
    {"mh", "Marshallese"},
    {"mn", "Mongolian"},
    {"na", "Nauru"},
    {"nv", "Navajo"},
    {"nd", "North Ndebele"},
    {"nr", "South Ndebele"},
    {"ng", "Ndonga"},
    {"ne", "Nepali"},
    {"no", "Norwegian"},
    {"nb", "Norwegian Bokmål"},
    {"nn", "Norwegian Nynorsk"},
    {"ii", "Nuosu"},
    {"oc", "Occitan"},
    {"oj", "Ojibwe"},
    {"or", "Odia"},
    {"om", "Oromo"},
    {"os", "Ossetian"},
    {"pi", "Pali"},
    {"ps", "Pashto"},
    {"fa", "Persian"},
    {"pl", "Polish"},
    {"pt", "Portuguese"},
    {"pt-BR", "Portuguese (Brazil)"},
    {"pa", "Punjabi"},
    {"qu", "Quechua"},
    {"ro", "Romanian"},
    {"rm", "Romansh"},
    {"rn", "Rundi"},
    {"ru", "Russian"},
    {"se", "Northern Sami"},
    {"sm", "Samoan"},
    {"sg", "Sango"},
    {"sa", "Sanskrit"},
    {"sc", "Sardinian"},
    {"sr", "Serbian"},
    {"sn", "Shona"},
    {"sd", "Sindhi"},
    {"si", "Sinhala"},
    {"sk", "Slovak"},
    {"sl", "Slovenian"},
    {"so", "Somali"},
    {"st", "Southern Sotho"},
    {"es", "Spanish"},
    {"es-MX", "Spanish (Mexico)"},
    {"su", "Sundanese"},
    {"sw", "Swahili"},
    {"ss", "Swati"},
    {"sv", "Swedish"},
    {"tl", "Tagalog"},
    {"ty", "Tahitian"},
    {"tg", "Tajik"},
    {"ta", "Tamil"},
    {"tt", "Tatar"},
    {"te", "Telugu"},
    {"th", "Thai"},
    {"bo", "Tibetan"},
    {"ti", "Tigrinya"},
    {"to", "Tongan"},
    {"ts", "Tsonga"},
    {"tn", "Tswana"},
    {"tr", "Turkish"},
    {"tk", "Turkmen"},
    {"tw", "Twi"},
    {"ug", "Uyghur"},
    {"uk", "Ukrainian"},
    {"ur", "Urdu"},
    {"uz", "Uzbek"},
    {"ve", "Venda"},
    {"vi", "Vietnamese"},
    {"vo", "Volapük"},
    {"wa", "Walloon"},
    {"cy", "Welsh"},
    {"wo", "Wolof"},
    {"xh", "Xhosa"},
    {"yi", "Yiddish"},
    {"yo", "Yoruba"},
    {"za", "Zhuang"},
    {"zu", "Zulu"},
};

} // namespace tesseract::views
