#!/usr/bin/env python3
"""Generate a pseudolocale .po from a .pot file for i18n QA."""
import sys
import re


ACCENT_TABLE = str.maketrans('aeiouAEIOUcCnN', 'àéïöùÀÉÏÖÙçÇñÑ')


def pseudoize(s):
    """Apply accent substitution, add brackets and padding."""
    s = s.translate(ACCENT_TABLE)
    pad = max(1, len(s) // 5)
    return '[' + s + 'x' * pad + ']'


def unescape(s):
    """Remove surrounding quotes and unescape gettext C escapes."""
    return s.replace('\\n', '\n').replace('\\t', '\t').replace('\\"', '"').replace('\\\\', '\\')


def escape(s):
    """Escape for gettext msgstr value (excluding the surrounding quotes)."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t')


def parse_entries(lines):
    """Parse a .pot file into a list of (comments, msgid, msgid_plural, msgstr_list) tuples.

    Skips the header entry (msgid "").
    Returns list of dicts: {comments, msgid, msgid_plural, msgstrs}
    """
    entries = []
    i = 0
    n = len(lines)

    while i < n:
        # Skip blank lines
        if lines[i].strip() == '':
            i += 1
            continue

        # Collect comment lines
        comments = []
        while i < n and (lines[i].startswith('#') or lines[i].strip() == ''):
            if lines[i].strip():
                comments.append(lines[i])
            i += 1

        if i >= n:
            break

        # Parse msgid (possibly multiline)
        if not lines[i].startswith('msgid '):
            i += 1
            continue

        msgid = _collect_string(lines, i)
        i = _advance_past_string(lines, i)

        # Skip the header entry
        if msgid == '':
            # Skip until blank line or EOF
            while i < n and lines[i].strip() != '':
                i += 1
            continue

        # Optional msgid_plural
        msgid_plural = None
        if i < n and lines[i].startswith('msgid_plural '):
            msgid_plural = _collect_string(lines, i)
            i = _advance_past_string(lines, i)

        # Parse msgstr(s)
        msgstrs = []
        if i < n and lines[i].startswith('msgstr['):
            while i < n and lines[i].startswith('msgstr['):
                s = _collect_string(lines, i)
                msgstrs.append(s)
                i = _advance_past_string(lines, i)
        elif i < n and lines[i].startswith('msgstr '):
            s = _collect_string(lines, i)
            msgstrs.append(s)
            i = _advance_past_string(lines, i)

        entries.append({
            'comments': comments,
            'msgid': msgid,
            'msgid_plural': msgid_plural,
            'msgstrs': msgstrs,
        })

    return entries


def _collect_string(lines, i):
    """Collect a gettext string value starting at line i (e.g. msgid "...").
    Handles continuation lines."""
    # Extract after the keyword
    m = re.match(r'\w[\w\[\]0-9]* (".*")', lines[i])
    if not m:
        return ''
    parts = [unescape(m.group(1)[1:-1])]  # strip outer quotes
    i += 1
    while i < len(lines) and lines[i].startswith('"'):
        parts.append(unescape(lines[i].strip()[1:-1]))
        i += 1
    return ''.join(parts)


def _advance_past_string(lines, i):
    """Advance i past a keyword line and its continuation lines."""
    i += 1
    while i < len(lines) and lines[i].startswith('"'):
        i += 1
    return i


HEADER = '''\
# Pseudolocale for i18n QA — auto-generated by i18n-pseudo target
# Do not edit manually.
msgid ""
msgstr ""
"Language: x-pseudo\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\\n"
'''


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <input.pot> <output.po>", file=sys.stderr)
        sys.exit(1)

    pot_path, po_path = sys.argv[1], sys.argv[2]

    try:
        with open(pot_path, encoding='utf-8') as f:
            lines = f.readlines()
    except FileNotFoundError:
        print(f"Error: {pot_path} not found", file=sys.stderr)
        sys.exit(1)

    entries = parse_entries(lines)

    with open(po_path, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        for entry in entries:
            f.write('\n')
            for comment in entry['comments']:
                f.write(comment)
            if entry['msgid_plural'] is not None:
                f.write(f'msgid "{escape(entry["msgid"])}"\n')
                f.write(f'msgid_plural "{escape(entry["msgid_plural"])}"\n')
                # Generate two plural forms
                f.write(f'msgstr[0] "{escape(pseudoize(entry["msgid"]))}"\n')
                f.write(f'msgstr[1] "{escape(pseudoize(entry["msgid_plural"]))}"\n')
            else:
                f.write(f'msgid "{escape(entry["msgid"])}"\n')
                f.write(f'msgstr "{escape(pseudoize(entry["msgid"]))}"\n')


if __name__ == '__main__':
    main()
